### PR TITLE
Build: Replaced JSCS and JSHint with ESLint.

### PR DESCRIPTION
**Pull request by EricDunsworth**
* Updated package.json dependencies.
* Replaced the "jshint" and "jscs" tasks with an "eslint" task.
* Setup the "estlint" task to inherit its configuration settings from the wet-boew dependency's .eslintrc.json and .eslintrc.ci.json files.
* Updated src/theme.js to pass linting.
* Modified the "test" task to reference the "eslint" task.
* Removed a JSHint configuration file (.jshintrc).
* This is mostly a port of wet-boew/wet-boew#7456, along with some of wet-boew/wet-boew#7948's updates.
* Related to wet-boew/GCWeb#1312.

@nschonni @LaurentGoderre FYI.

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
Please rebase

**Comment by EricDunsworth** [comment]
@LaurentGoderre It doesn't look like this nor the other PRs you asked me to rebase are currently running into merge conflicts.

Travis-CI should start passing if you or another maintainer manually restarts it for this and the other PRs. Or do you just want me to rebase to trick Travis-CI into restarting? I can rebase them if that's what you had in mind.

**Comment by LaurentGoderre** [comment]
@EricDunsworth it's not about conflict, restarting the build wont fix the broken build because this branch doesn't have the sasslint fix.

**Comment by EricDunsworth** [comment]
@LaurentGoderre Just rebased and force pushed all of my open usability theme PRs :)!

Btw isn't Travis-CI supposed to build something along the lines of a pre-merged PR? IMO it wouldn't be very useful if its builds were solely based on the PR's commits without any consideration for whether it'd still be build-able after being merged into upstream.

I dug around a bit in Travis-CI's documentation and found more info about how it works:

[Travis-CI: Building Pull Requests - How Pull Requests are Tested](https://docs.travis-ci.com/user/pull-requests/#How-Pull-Requests-are-Tested)
> Rather than test the commits that have been pushed to the branch the pull request is from, we test the merge between the origin and the upstream branch. To only build on push events, you can disable Build on Pull Requests from your repository settings.

[Travis-CI: Building Pull Requests - My Pull Request isn’t being built](https://docs.travis-ci.com/user/pull-requests/#My-Pull-Request-isn%E2%80%99t-being-built)
> Travis CI also currently doesn’t build pull requests when the upstream branch is updated. When this happens, GitHub will update the merge commit between the downstream and upstream branch, and send out a notifications. But Travis CI currently ignores this update, as it could lead to a large number of new builds on repositories with lots of pull requests and lots of updates on the upstream branches.

So I guess Travis-CI builds are based on pre-merged PRs, but are only built automatically when a PR is first sent, when new commits are added to it or when it gets rebased. PRs aren't automatically rebuilt if commits are added to upstream after-the-fact. Travis-CI would need to either be manually restarted or the PR would need to be rebased (like what what done here) to trigger a new automatic build.

**Comment by LaurentGoderre** [comment]
It's worth testing the restart next time

**Pull request merged**
