### PR TITLE
Update build dependencies

### PR DESCRIPTION
**Pull request by nschonni**
Update the build dependencies to match those in the upstream repo.

### CODE REVIEW

**Comment by nschonni** [comment]
@delisma I was able to get this working on my machine. I did have some issues cleaning out my `lib` path at the beginning because of some "path too long" when running `rm -rf lib`
You could try and build this branch locally to see if you still hit those from #221

**Comment by LaurentGoderre** [comment]
@nschonni can you please do this for all themes?

**Comment by delisma** [comment]
Thanks @nschonni, I've recloned everything in a new folder and rerun it. It does work now.

**Comment by nschonni** [comment]
@andre-gh this should have landed instead of #224, but I'll rebase out the conflicts now.

**Comment by nschonni** [comment]
@LaurentGoderre I'll try to look at the other themes, but it takes awhile to actually compare the diffs in the outputs to validate nothing is functionally changing.
I'll let you merge if the rebased version still looks ok to you

**Comment by LaurentGoderre** [comment]
Is there any diff for this change, except for the explicit html changes?

**Comment by nschonni** [comment]
@LaurentGoderre Yes, the larger diff was for the node-sass update, but that got rebased out since the later PR got merged.

**Comment by LaurentGoderre** [comment]
So there is no diff left?

**Pull request closed without merging**
